export const ProductList = [
  {
    id: 1,
    title: "Pokémon Legend Arceus",
    description: "A pokémon rpg set in the past of Japan",
    price: 14000,
    image: "./productscoverart/pokemonarceus.jpg",
    stock: 12,
    category: "nintendo",
  },
  {
    id: 2,
    title: "Bravely Default 2",
    description: "High-fantasy rpg made by Square-Enix",
    price: 14000,
    image: "./productscoverart/bravelydefault2.jpg",
    stock: 20,
    category: "nintendo",
  },
  {
    id: 3,
    title: "Tokyo Mirage Sessions",
    description: "Turn based RPG that is a crossover between FE y SMT",
    price: 14000,
    image: "./productscoverart/tokyomiragesessions.jpg",
    stock: 4,
    category: "nintendo",
  },
  {
    id: 4,
    title: "Final Fantasy XIV",
    description: "The most acclaimed modern MMORPG",
    price: 12000,
    image: "./productscoverart/ffxiv.jpg",
    stock: 44,
    category: "playstation",
  },
  {
    id: 5,
    title: "Persona 5 Royal",
    description: "The upgraded version of the modern classic Persona 5",
    price: 12000,
    image: "./productscoverart/persona5.jpg",
    stock: 11,
    category: "playstation",
  },
  {
    id: 6,
    title: "Dead by Daylight",
    description: "A multiplayer horror slayer (Adults Only)",
    price: 12000,
    image: "./productscoverart/dbd.jpg",
    stock: 7,
    category: "playstation",
  },
  {
    id: 7,
    title: "Sunset Overdrive",
    description: "A satirical shooter open world",
    price: 10000,
    image: "./productscoverart/sunsetoverdrive.jpg",
    stock: 9,
    category: "xbox",
  },
  {
    id: 8,
    title: "Halo: The Master Chief Collection",
    description: "A bundle that contains the most prominent Halo games",
    price: 10000,
    image: "./productscoverart/halo.jpg",
    stock: 19,
    category: "xbox",
  },
  {
    id: 9,
    title: "Quantum",
    description:
      "One of the most acclaimed xbox console exclusives full packed of action",
    price: 10000,
    image: "./productscoverart/quantumbreak.jpg",
    stock: 1,
    category: "xbox",
  },
];
